name: Automatic Rebase
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  rebase:
    name: Rebase `staging` with `main`
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # otherwise, you will fail to push refs to dest repo
          ref: staging  # Working in the `staging` branch
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git rebase origin/main
          git push origin staging --force
